// <auto-generated />
using System;
using Lesson1.GraphQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lesson1.GraphQL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250317105521_ChangedPersonModel")]
    partial class ChangedPersonModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lesson1.GraphQL.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00b3a99c-e647-4427-8f5b-07f56de905d2"),
                            Age = 21,
                            Job = "Job 1",
                            Name = "Person 1"
                        },
                        new
                        {
                            Id = new Guid("b60fa1de-82c7-4dea-895f-f0f4c89d6a0c"),
                            Age = 21,
                            Job = "Job 1",
                            Name = "Person 2"
                        },
                        new
                        {
                            Id = new Guid("c628b519-9875-435e-a8c4-add09561e8bc"),
                            Age = 31,
                            Job = "Job 1",
                            Name = "Person 3"
                        },
                        new
                        {
                            Id = new Guid("fea55368-5857-403e-93b0-c2f14232bc1b"),
                            Age = 41,
                            Job = "Job 2",
                            Name = "Person 4"
                        },
                        new
                        {
                            Id = new Guid("cf164e63-0ad8-4731-ad38-dc2395190a42"),
                            Age = 20,
                            Job = "Job 2",
                            Name = "Person 5"
                        },
                        new
                        {
                            Id = new Guid("718ebe90-41e4-4b00-a3da-5dad0aedae03"),
                            Age = 30,
                            Job = "Job 2",
                            Name = "Person 6"
                        },
                        new
                        {
                            Id = new Guid("490e0284-bae9-45f4-b680-e69cce13d546"),
                            Age = 40,
                            Job = "Job 3",
                            Name = "Person 7"
                        },
                        new
                        {
                            Id = new Guid("86681787-1f41-4eaf-9139-f64b9db800e8"),
                            Age = 19,
                            Job = "Job 3",
                            Name = "Person 8"
                        },
                        new
                        {
                            Id = new Guid("7c693a57-1142-4d61-a329-9dced10f9788"),
                            Age = 18,
                            Job = "Job 3",
                            Name = "Person 9"
                        },
                        new
                        {
                            Id = new Guid("2cc91448-a121-41ae-9a8c-7ebe975811e7"),
                            Age = 100,
                            Job = "Job 1",
                            Name = "Person 10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
