// <auto-generated />
using Lesson1.GraphQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lesson1.GraphQL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250316130130_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lesson1.GraphQL.Entities.Person", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Name = "Person 1",
                            Age = 21,
                            Job = "Job 1"
                        },
                        new
                        {
                            Name = "Person 2",
                            Age = 21,
                            Job = "Job 1"
                        },
                        new
                        {
                            Name = "Person 3",
                            Age = 31,
                            Job = "Job 1"
                        },
                        new
                        {
                            Name = "Person 4",
                            Age = 41,
                            Job = "Job 2"
                        },
                        new
                        {
                            Name = "Person 5",
                            Age = 20,
                            Job = "Job 2"
                        },
                        new
                        {
                            Name = "Person 6",
                            Age = 30,
                            Job = "Job 2"
                        },
                        new
                        {
                            Name = "Person 7",
                            Age = 40,
                            Job = "Job 3"
                        },
                        new
                        {
                            Name = "Person 8",
                            Age = 19,
                            Job = "Job 3"
                        },
                        new
                        {
                            Name = "Person 9",
                            Age = 18,
                            Job = "Job 3"
                        },
                        new
                        {
                            Name = "Person 10",
                            Age = 100,
                            Job = "Job 1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
